version: '3'
services:
  dinoes-fe:
    container_name: dinoes-fe
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/src:cached

volumes:
  dinoes_data:
