name: Build and deploy Node.js app to Azure Web App - canal2-diffusion-frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Ensure package-lock.json exists
        run: |
          if [ ! -f package-lock.json ]; then
            npm install --package-lock-only
          fi

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: package-lock.json # Ensures caching only if lock file exists

      - name: Clean and reinstall dependencies
        run: |
          rm -rf node_modules
          npm install -g npm@latest
          npm install

      - name: Update dependencies
        run: |
          npm update
          npm install @pinia/nuxt@latest pinia-plugin-persistedstate@latest
          npm uninstall @pinia-plugin-persistedstate/nuxt || true

      - name: Fix security vulnerabilities
        run: npm audit fix --force || true

      - name: npm build
        run: |
          npm run build --if-present
          echo "Tests skipped during build process"

      # Step to remove Docker-related files
      - name: Remove Docker files
        run: |
          find . -name "Dockerfile*" -exec rm -f {} +
          find . -name ".dockerignore" -exec rm -f {} +
          find . -name "docker-compose*.yml" -exec rm -f {} +

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_50FD266671AB4485B139F4DBE068CA23 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F53C78348FE74466A01CA0CE1DE71C70 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E15D7BD2FCCB40C4AC9B9231709C2EEC }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'canal2-diffusion-frontend'
          slot-name: 'Production'
          package: .
